### ISSUE TITLE
Please add comments

### ISSUE THREAD

**Issue by neilbalch** [DeepVisionFRC/2018RobotCode#1]
Also please respect the 2 or even 4 space indentation rule. [Google Style Guide for C++](https://google.github.io/styleguide/cppguide.html)

**Comment by nitroxplunge** [comment]
This version of the code is very outdated, updated code will be uploaded after SVR. I will make sure to follow conventions better, didn't expect anyone else to read my code ¯\_(ツ)_/¯

**Comment by neilbalch** [comment]
Lol. I understand. Closed until I feel like reopening. 😈

**Comment by nitroxplunge** [comment]
A completely re-written and commented version of this code can now be found at https://github.com/frc7308/robot2018-rewritten.
